# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hello. I'm Kelly Savietta."
# email: 'jami0821@gmail.com'
description: "I'm a software developer who likes to create useful things for the web."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ksavietta.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: 'ksavietta'
linkedin_username: 'ksavietta'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

### Phantom settings
paginate: 10
enable_contact: false

#### Phantom Navigation menu
admin_name: 'Kelly Savietta'
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
