remote_theme: jamigibbs/phantom
title: "Hello. I'm Kelly Savietta."
# email: 'ksavietta@gmail.com'
description: "I'm a software developer. I like to create useful things for the web."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ksavietta.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: 'ksavietta'

enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
